config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  devise_for :users
  resources :users, only: :show
    resources :recipes
       resources :materials
        resources :cooks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook.rb
class Cook < ApplicationRecord

    belongs_to :recipe, optional: true
    mount_uploader :cooking_image, ImageUploader
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe, optional: true
  
  
  
  validates :name, presence: true
  validates :quantity, presence: true
  # validates :material_id, presence: true
  # validates :recipe_id, presence: true
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
   belongs_to :user
   mount_uploader :image, ImageUploader
   has_many :materials,dependent: :destroy
   has_many :cooks, dependent: :destroy
  accepts_nested_attributes_for :materials, allow_destroy: true
  accepts_nested_attributes_for :cooks, allow_destroy: true
  


  validates :title, presence: true
  validates :image, presence: true
  # validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
         PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
         validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください' 
        
        with_options presence: true do
             validates :nickname
             validates :email,:password,:password_confirmation
        end

        has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    # @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)
    # content: params[:content],
    # user_id: @current_user.id
    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def material_params
      params.require(:material).permit(:material_name, :material_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.includes(:user)
    @recipes = Recipe.all.order(id: :DESC)
    @recipes = Recipe.all.page(params[:page]).order(id: :DESC).per(6)    
    @materials = Material.all.order(recipe_id: :DESC)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @materials = @recipe.materials
    @cooks = @recipe.cooks
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @material = @recipe.materials.build
    @cook = @recipe.cooks.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    # @recipe.materials = params[:material_id]
    # @material = @recipe.materials.build
    # respond_to do |format|
    if @recipe.save
      redirect_to @recipe
      # format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
      # format.json { render :show, status: :created, location: @recipe }
    else
      render :new
      # format.html { render :new }
      # format.json { render json: @recipe.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :image,
                                      materials_attributes: [:id, :name, :quantity, :recipe_id, :_destroy],
                                      cooks_attributes: [:id, :content, :cooking_image, :recipe_id, :_destroy]).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookDodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400&display=swap');
   </style>
  </head>
  <body>
    <%= render "./shared/top_header" %>
    <div class="container">
      <%= yield %>
    </div>
    <footer class="footer">
      <div class="container">
        <p class="copyright">
          Copyright CookDodo 2021.
        </p>
      </div>
    </footer>
  </body>
</html>

app/views/materials/_form.html.erb
<%#<%= form_with(model: material, local: true) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
        <% material.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form', material: @material %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form', material: @material %>
<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>

app/views/recipes/_cook_fields.html.erb
 

<div class="nested-fields">
  <div class="card cook_content border-0">
    <div class="card-body">
      <div class="input-field">
        <%= f.text_area :content, maxlength:"60", size: "20x3", class: "cook_content border-5 rounded", placeholder: "調理内容を入力してください", id:"data-recipe-id" %>
        残り<span class="input-field__count" data-count="10"></span>文字
      </div>
       
      
    <div class="input-group mb-3 border-0">  
       <%= f.file_field :cooking_image, id:"customFile", class:"custom-file-input"%>
      <label for="customFile" class="custom-file-label" data-browse="参照"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-camera-fill" viewBox="0 0 16 16">
            <path d="M10.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
            <path d="M2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2zm.5 2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm9 2.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"/>
            </svg>調理画像...</label>     
        <%= link_to_remove_association "❌", f, class:"btn btn-outline-secondary border-0"%>           
     </div>   
    </div>      
  </div>
</div>
<script>
$('.custom-file-input').on('change',function(){
  $(this).next('.custom-file-label').html($(this)[0].files[0].name);
});
</script>

<script>
$(function(){
  function countInputText(input) {
    //文字数を表示する.input-field__countを取得
    var counter = $(input).parents('.input-field').find(".input-field__count");

    // データ属性(data-count)から最大文字数を取得
    var maxLength = counter.data("count");

    // 現在の文字数を取得
    var currentLength = 60 - $(input).val().length;
    var htmlVal = currentLength;

   // 現在の文字数と最大文字数を比較して、
   // 現在の文字数が多ければ赤く表示する
    if ( parseInt(currentLength) <= parseInt(maxLength) ) {
      counter.html("<span style='color:red'>" + htmlVal + "</span>");
    } else {
      counter.html(htmlVal);
    }
  }

  // ページ表示時に文字数をカウントして表示
  $('textarea, input[type=text]').each(function(){
    countInputText($(this));
  });

  // フォーム入力時に文字数をカウントして表示
  $('textarea, input[type=text]').on('keydown keyup keypress change',function(){
    countInputText($(this));
  });
});
</script>

 

app/views/recipes/_form.html.erb
<%= form_with(model: @recipe, local: true) do |f| %>
<% if @recipe.errors.any? %>
  <div id="error_explanation", class="error-pr">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<div class="p-4 bg-light">
  <div class="row ma-2 top-wrapper">
    <div class="col-sm-4">
      <div class="card">
         <div class='image_wrapper'>
          <div class="mb-3">
          <label for="message_image" class="form-label"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-camera-fill" viewBox="0 0 16 16">
            <path d="M10.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
            <path d="M2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2zm.5 2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm9 2.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"/>
            </svg> << 料理の画像を載せて下さい</label>
           <%= f.file_field :image, id:"message_image", class:"form-control form-control-sm", style:"display: none;"%>
            <div id='image-list', class="image-ls"></div>
          </div>
         
         
      
          </div>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="card">
        <div class="card-body">
           <div class="input-field">
        <%= f.text_area :title, class: "cook-name border-5 rounded", placeholder: "料理名を入力してください", size: "10x4", maxlength:"60", id:"data-recipe-id" %>
        残り<span class="input-field__count" data-count="10"></span>文字
      </div>  
        </div>
      </div>
    </div>
  </div>
  <div class="row ma-2">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body material-l">
          <h5 class="card-title"> 
             <div id="links">
                <%= link_to_add_association 'クリックして材料を追加',f, :materials,
                class: 'add_fields',
                id: 'Links',
                data: {
                association_insertion_node: '#detail-association-insertion-point',
                association_insertion_method: 'before'
                } %>
              </div> 
              <div id="materials", class="materials_list">
                <%= f.fields_for :materials do |material| %>
                <%= render 'material_fields',f: material %>
                <% end %>
              </div>          
              <div id="detail-association-insertion-point" class="nazo2"></div>
              </h5>
              </div> 
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">
          <div id="link">            
                <%= link_to_add_association '調理内容を追加',f, :cooks,
                  class: 'add_fields',
                  id: 'Link',
                  data: {
                  association_insertion_node: '#detail-association-insertion-point2',
                  association_insertion_method: 'before'
                  } %>
              </div>        
              <div id="cooks", class="cook-list">
                <%= f.fields_for :cooks do |cook| %>
                <%= render 'cook_fields',f: cook %>  
                <% end %>
              </div>
           <div id="detail-association-insertion-point2" class='add_cook'></div>
         </h5>
        </div>
      </div>
    </div>
  </div>
</div>
<div class='bottom_wrapper'>
  <div class="actions">
    <%= f.submit "レシピを公開する", class:"btn btn-outline-dark recipe-btn" %>
  </div>
</div>
<% end %>

app/views/recipes/_material_fields.html.erb
<div class="nested-fields matarial-margin">
   <div class="card border-0" >  
     <div class="input-group border-bottom">
            <%= f.text_field :name, placeholder: "材料を入力", class:"form-control border-0 mt-name"%>
            <%= f.text_field :quantity, placeholder: "分量を入力", class:"form-control border-0 qt-name"%>
            <%= link_to_remove_association "❌", f, class:"btn btn-outline-secondary border-0" %>  
      </div>
   </div>
</div>

app/views/recipes/edit.html.erb
<%= form_with(model: @recipe, local: true) do |f| %>
<% if @recipe.errors.any? %>
  <div id="error_explanation", class="error-pr">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<div class="p-4 bg-light">
  <div class="row ma-2 top-wrapper">
    <div class="col-sm-4">
      <div class="card">
         <div class='image_wrapper'>
          <div class="mb-3">
          <label for="message_image" class="form-label"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-camera-fill" viewBox="0 0 16 16">
            <path d="M10.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
            <path d="M2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2zm.5 2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm9 2.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"/>
            </svg> << ※料理の画像を載せて下さい※</label>
           <%= f.file_field :image, id:"message_image", class:"form-control form-control-sm", style:"display: none;"%>
            <div id='image-list', class="image-ls"></div>
          </div>
         
         
      
          </div>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="card">
        <div class="card-body">
          <%= f.text_area :title, class: "cook-title", placeholder: "料理名を入力してください", size: "10x4" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row ma-2">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body material-l">
            <h5 class="card-title"> 
             <div id="links">
                <%= link_to_add_association 'クリックして材料を追加',f, :materials,
                class: 'add_fields',
                id: 'Links',
                data: {
                association_insertion_node: '#detail-association-insertion-point',
                association_insertion_method: 'before'
                } %>
              </div>        
              <div id="materials", class="materials_list">
                <%= f.fields_for :materials do |material| %>
                <%= render 'material_fields',f: material %>
                <% end %>
              </div>
              </div>
                <div class="nazo2">
              <div id="detail-association-insertion-point" class="nazo2"></div>
             </h5>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">
          <div id="link">            
                <%= link_to_add_association '調理内容を追加',f, :cooks,
                  class: 'add_fields',
                  id: 'Link',
                  data: {
                  association_insertion_node: '#detail-association-insertion-point2',
                  association_insertion_method: 'before'
                  } %>
              </div>         
              <div id="cooks", class="cook-list">
                <%= f.fields_for :cooks do |cook| %>
                <%= render 'cook_fields',f: cook %>
                <% end %>
              </div>
           <div id="detail-association-insertion-point2" class='add_cook'></div>
         </h5>
        </div>
      </div>
    </div>
  </div>
</div>
<div class='bottom_wrapper'>
  <div class="actions">
    <%= f.submit "レシピを公開する", class:"btn btn-outline-dark recipe-btn" %>
  </div>
</div>
<% end %>

app/views/recipes/index.html.erb
<div class="container-fluid index_main img-fluid">
   <div class="container index_img">
     <div class="card bg-dark text-white border-0">
          <%= image_tag '/images/back.png', class:"index-header", alt: '猫の画像' %>
        <div class="card-img-overlay"> 
          <h2 class="card-title top-title ">きょうは何をつくろう</h2>
          <h2 class="card-title top-title text-right ">買い忘れはないかな？</h2>      
          <p class="card-text header-text">思い立った突然の買い物に</p>
          <p class="card-text header-text" >買い忘れの悲しみに</p>
          <p class="card-text header-text">cook do! do!が力になります</p>
        </div>
      </div>
    </div>
  
   <div class="container recipe-list"> 

   <h2>新着レシピ一覧</h2><%= paginate @recipes %>
    
         
       <div class="card mb-3", style="max-width: 540px;"> 
         <div class="row g-0 ">
            <% @recipes.each do |recipe| %>
             
          
            <div class="col-md-4">
              <%= link_to image_tag("#{recipe.image}", class:"card-img-top"), recipe, method: :get %>
            </div>
            <div class="col-md-8 ">
              <div class="card-body">
                <h5 class="card-title"><%= recipe.title %></h5>  
                  <p class="card-text"><small class="text-muted">by <%= recipe.user.nickname %></small></p>
              </div>
            </div>
            <% end %>
          </div>
        </div>   
        </div> 
    
</div> 
      
    
    

app/views/recipes/new.html.erb
<%= render 'form', recipe: @recipe %>

app/views/recipes/show.html.erb
 <div class="p-4 bg-light">
      <div class="row">
        <div class="col-sm-6">
          <div class="card card border-light mb-3">
             <div class="card-body cook-title">
               <h2 class="card-title"><%= @recipe.title %></h2>
               <%= image_tag @recipe.image.url, class:"card-img-top" %>
            </div>
          </div>  
        </div>  
        <div class="col-sm-6 show-material">
          <div class="card quantity border-0" >
          <h2 class="text-center">材料</h2>
          <% @materials.each do |material| %>
           <div>
          <label class="list-group-item border-0"><ul class="list-group list-group-horizontal border-bottom">
              <li class="list-group-item border-0"><%= check_box_tag material.name %></li>
              <li class="list-group-item border-0"><%= material.name %></li>
              <li class="list-group-item border-0" ><%= material.quantity %></li>
            </ul></label>
           </div>
            <%end%>
            </div>
        </div>
    </div>
    <div class="p-4 bg-light">  
        <h4>作り方</h4>    
         <% index = 0 %>
       <div class="row">
          <% @cooks.each do |cook| %>
         <div class="col-sm-3">
           <div class="card card border-light mb-3">
             <div class="card-body cook-title">
               <h5 class="card-title"><%= index += 1 %></h5>
               <%= image_tag "#{cook.cooking_image.url}", class:"card-img-top"%>
               <p class="card-text cook-method"><%= cook.content %></p>
             </div>
          </div>
        </div>
          <%end%>          
       </div>
        <div class="col-sm-3">
      </div>
    </div>
     <% if user_signed_in? %>
     <% if @recipe.user == current_user %>
    <%= link_to 'このレシピを編集する', edit_recipe_path(@recipe) %>
    <%= link_to 'このレシピを削除する', @recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end  %>
  

   

































        
                

    

app/views/shared/_error_messages.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul class="error-list">
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

app/views/shared/_header.erb
<header class='header'>
 <%= link_to image_tag("cook-do1.png", class:"logo"), "/" %> 
</header>

app/views/shared/_top_header.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #E6FFE9;">
    <div class="container-fluid">
      <a class="navbar-brand">
        <%= link_to image_tag("cook-do1.png", class:"d-inline-block align-top cook-do1", width:"30", height:"24"), "/" %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'レシピを作成する', '/recipes/new', method: :get, class: "nav-link active" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" id="dropdownMenuButton" role="button" data-bs-toggle="dropdown"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.nickname %>
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" id="dropdownMenuButton" role="button" data-bs-toggle="dropdown"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ログイン/ユーザー登録
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'ログイン', new_user_session_path, method: :get, class: "dropdown-item" %>
                <%= link_to '新規登録', new_user_registration_path, method: :get, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>